const REDUX_CONSTANTS = {
    SAVE_USER: 'SAVE_USER',
    REMOVE_USER: 'REMOVE_USER',

    MOST_POPULAR_VIEWED_1: 'MOST_POPULAR_VIEWED_1',
    MOST_POPULAR_VIEWED_7: 'MOST_POPULAR_VIEWED_7',
    MOST_POPULAR_VIEWED_30: 'MOST_POPULAR_VIEWED_30',

    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE'
}


export default REDUX_CONSTANTS;